In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

data_frame = pd.read_csv("data.csv")

data_frame.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,accommodates,bathrooms,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,1.878200e+04,1.878200e+04,1.878200e+04,18726.000000,18726.000000,0.0,18782.000000,18782.000000,18782.000000,0.0,...,16221.000000,16229.000000,16223.000000,16223.000000,0.0,18782.000000,18782.000000,18782.000000,18782.000000,16492.000000
mean,2.026571e+07,2.020101e+13,6.490719e+07,2.733312,2.733312,NaN,52.365471,4.889641,2.845810,NaN,...,9.756489,9.800850,9.516982,9.203107,NaN,2.582047,2.049675,0.465872,0.013311,0.701629
std,1.256165e+07,0.000000e+00,8.311726e+07,12.945250,12.945250,NaN,0.016496,0.035922,1.285286,NaN,...,0.646537,0.619717,0.701245,0.823080,NaN,8.630081,8.443451,1.390323,0.214320,1.327302
min,2.818000e+03,2.020101e+13,3.159000e+03,0.000000,0.000000,NaN,52.289270,4.755720,1.000000,NaN,...,2.000000,2.000000,2.000000,2.000000,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,9.965431e+06,2.020101e+13,9.134263e+06,1.000000,1.000000,NaN,52.355130,4.863880,2.000000,NaN,...,10.000000,10.000000,9.000000,9.000000,NaN,1.000000,1.000000,0.000000,0.000000,0.140000
50%,1.893914e+07,2.020101e+13,2.729216e+07,1.000000,1.000000,NaN,52.364740,4.887030,2.000000,NaN,...,10.000000,10.000000,10.000000,9.000000,NaN,1.000000,1.000000,0.000000,0.000000,0.330000
75%,2.991968e+07,2.020101e+13,8.445316e+07,1.000000,1.000000,NaN,52.375370,4.909390,4.000000,NaN,...,10.000000,10.000000,10.000000,10.000000,NaN,1.000000,1.000000,0.000000,0.000000,0.680000
max,4.578300e+07,2.020101e+13,3.711601e+08,892.000000,892.000000,NaN,52.425120,5.068080,16.000000,NaN,...,10.000000,10.000000,10.000000,10.000000,NaN,86.000000,85.000000,16.000000,6.000000,47.610000